const ITEM_SPRITE_BASE_URL = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items';

const MEGA_STONE_BY_FORM = Object.freeze({
  'venusaur-mega': 'venusaurite',
  'charizard-mega-x': 'charizardite-x',
  'charizard-mega-y': 'charizardite-y',
  'blastoise-mega': 'blastoisinite',
  'beedrill-mega': 'beedrillite',
  'pidgeot-mega': 'pidgeotite',
  'alakazam-mega': 'alakazite',
  'slowbro-mega': 'slowbronite',
  'gengar-mega': 'gengarite',
  'kangaskhan-mega': 'kangaskhanite',
  'pinsir-mega': 'pinsirite',
  'gyarados-mega': 'gyaradosite',
  'aerodactyl-mega': 'aerodactylite',
  'mewtwo-mega-x': 'mewtwonite-x',
  'mewtwo-mega-y': 'mewtwonite-y',
  'ampharos-mega': 'ampharosite',
  'steelix-mega': 'steelixite',
  'scizor-mega': 'scizorite',
  'heracross-mega': 'heracronite',
  'houndoom-mega': 'houndoominite',
  'tyranitar-mega': 'tyranitarite',
  'sceptile-mega': 'sceptilite',
  'blaziken-mega': 'blazikenite',
  'swampert-mega': 'swampertite',
  'gardevoir-mega': 'gardevoirite',
  'sableye-mega': 'sablenite',
  'mawile-mega': 'mawilite',
  'aggron-mega': 'aggronite',
  'medicham-mega': 'medichamite',
  'manectric-mega': 'manectite',
  'sharpedo-mega': 'sharpedonite',
  'camerupt-mega': 'cameruptite',
  'altaria-mega': 'altarianite',
  'banette-mega': 'banettite',
  'absol-mega': 'absolite',
  'glalie-mega': 'glalitite',
  'salamence-mega': 'salamencite',
  'metagross-mega': 'metagrossite',
  'latias-mega': 'latiasite',
  'latios-mega': 'latiosite',
  'lopunny-mega': 'lopunnite',
  'garchomp-mega': 'garchompite',
  'lucario-mega': 'lucarionite',
  'abomasnow-mega': 'abomasite',
  'gallade-mega': 'galladite',
  'audino-mega': 'audinite',
  'diancie-mega': 'diancite',

  'clefable-mega': 'clefablite',
  'victreebel-mega': 'victreebelite',
  'starmie-mega': 'starminite',
  'dragonite-mega': 'dragoninite',
  'meganium-mega': 'meganiumite',
  'feraligatr-mega': 'feraligite',
  'skarmory-mega': 'skarmorite',
  'froslass-mega': 'froslassite',
  'emboar-mega': 'emboarite',
  'excadrill-mega': 'excadrite',
  'scolipede-mega': 'scolipite',
  'scrafty-mega': 'scraftinite',
  'eelektross-mega': 'eelektrossite',
  'chandelure-mega': 'chandelurite',
  'chesnaught-mega': 'chesnaughtite',
  'delphox-mega': 'delphoxite',
  'greninja-mega': 'greninjite',
  'pyroar-mega': 'pyroarite',
  'floette-mega': 'floettite',
  'malamar-mega': 'malamarite',
  'barbaracle-mega': 'barbaracite',
  'dragalge-mega': 'dragalgite',
  'hawlucha-mega': 'hawluchanite',
  'zygarde-mega': 'zygardite',
  'drampa-mega': 'drampanite',
  'falinks-mega': 'falinksite',
  'raichu-mega-x': 'raichunite-x',
  'raichu-mega-y': 'raichunite-y',
  'chimecho-mega': 'chimechite',
  'absol-mega-z': 'absolite-z',
  'staraptor-mega': 'staraptite',
  'garchomp-mega-z': 'garchompite-z',
  'lucario-mega-z': 'lucarionite-z',
  'heatran-mega': 'heatranite',
  'darkrai-mega': 'darkranite',
  'golurk-mega': 'golurkite',
  'meowstic-male-mega': 'meowsticite',
  'meowstic-female-mega': 'meowsticite',
  'crabominable-mega': 'crabominite',
  'golisopod-mega': 'golisopite',
  'magearna-mega': 'magearnite',
  'magearna-original-mega': 'magearnite',
  'zeraora-mega': 'zeraorite',
  'scovillain-mega': 'scovillainite',
  'glimmora-mega': 'glimmoranite',
  'tatsugiri-curly-mega': 'tatsugirinite',
  'tatsugiri-droopy-mega': 'tatsugirinite',
  'tatsugiri-stretchy-mega': 'tatsugirinite',
  'baxcalibur-mega': 'baxcalibrite',
});

export const getMegaStone = (formName = '') => {
  const stoneName = MEGA_STONE_BY_FORM[formName];

  if (!stoneName) {
    return null;
  }

  return {
    name: stoneName,
    sprite: `${ITEM_SPRITE_BASE_URL}/${stoneName}.png`,
  };
};

export const hasMegaStone = (formName = '') => Boolean(MEGA_STONE_BY_FORM[formName]);
